sudo: required
services: 
  - docker

before_install:
  - docker build -t test-image -f Dockerfile.dev .

script:
  - docker run test-image npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket-name: "my-bucket-name"
  bucket-path: "docker"
  on:
    branch: master
